version: "3.8"

services:
  api-service:
    container_name: api-service
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    restart: unless-stopped
